[run_settings]
# list of board URLs
boards = ["dig2://caendgtz-usb-25380", "dig2://caendgtz-usb-25379"]
# run duration in seconds
run_duration = 20
output_dir = "/home/lardaq/Documents/testing"
campaign_num = 0

# default values that don't need to be included
# blosc_threads = 5
# compression_level = 2

[board_settings]
# en_chans can be either true for all channels or a list
# of channels to enable
# en_chans = [1]
en_chans = true

# record_len is the waveform length in samples
record_len = 4125

# pre_trig_len is pre-trigger length in samples
pre_trig_len = 100

# trig_source = "TrgIn"
trig_source = "SwTrg | TestPulse" # TrgIn is another option
io_level = "TTL"
test_pulse_period = 8333333
test_pulse_width = 1000
test_pulse_low = 0
test_pulse_high = 10000

# dc_offset can be a single number for each channel
# or a map for each channel
# [board_settings.dc_offset]
# "1" = 20.0
# "2" = 30.0
# "50" = 50.0
dc_offset = 50.0

# trigger threshold can be a single number for each
# channel or a map for each channel in the range
# -65536..65536 in ADC units
# [board_settings.trig_thr]
# "1" = -20
# "2" = -40
trig_thr = -20

# trigger threshold mode can be chosen for all
# channels or each individual channel
# [board_settings.trig_thr_mode]
# "1" = "Relative"
# "2" = "Absolute"
trig_thr_mode = "Relative" # or "Absolute"

# trigger edge can be chosen for all
# channels or each individual channel
# [board_settings.trig_edge]
# "1" = "Rise"
# "2" = "Fall"
trig_edge = "Fall" # or "Rise"

# samples over threshold can be chosen for all
# channels or per-channel basis
# 0..65535
# [board_settings.samples_over_thr]
# "1" = 4
# "2" = 10
samples_over_thr = 5

itl_logic = "OR"        # or "AND" or "Majority"
itl_majority_level = 4  # how many channels to include in majority
itl_pair_logic = "NONE" # or "OR" or "AND"
itl_polarity = "Direct" # or "Inverted"
itl_gatewidth = 1000    # ns
itl_retrig = "True"     # or "False"

# which channels to include in ITL logic
# [board_settings.itl_connect]
# "1" = "ITLA"
# "2" = "Disabled"
itl_connect = "ITLA" # or "Disabled"

[sync_settings]
primary_clock_src = "Internal"
primary_sync_out = "Run"
primary_start_source = "SWcmd"
primary_clock_out_fp = "True"
secondary_clock_src = "FPClkIn"
secondary_sync_out = "Disabled"
secondary_start_source = "EncodedClkIn"
secondary_clock_out_fp = "False"
auto_disarm = "True"
trig_out = "TrgIn"
run_delay = 0
clk_out_delay = 0
