[run_settings]
# run duration in seconds
run_duration = 30
output_dir = "/home/lardaq/Documents/testing"
campaign_num = 0

[board_settings]
# en_chans can be either true for all channels or a list
# of channels to enable
# en_chans = [1]
en_chans = true

# record_len is the waveform length in samples
# record_len = 33000
record_len = 4125

# pre_trig_len is pre-trigger length in samples
pre_trig_len = 1250
trig_source = "SwTrg | TestPulse" # TrgIn is another option

# dc_offset can be a single number for each channel
# or a map for each channel
# [board_settings.dc_offset]
# "1" = 20.0
# "2" = 30.0
# "50" = 50.0
dc_offset = 50.0

[sync_settings]
primary_clock_src = "Internal"
primary_sync_out = "Run"
primary_start_source = "SWcmd"
primary_clock_out_fp = "True"
secondary_clock_src = "FPClkIn"
secondary_sync_out = "Disabled"
secondary_start_source = "EncodedClkIn"
secondary_clock_out_fp = "False"
auto_disarm = "True"
trig_out = "TrgIn"
